Allow failures when trying to push the manual for an unofficial branch

diff --git a/.travis/pushdoc b/.travis/pushdoc
--- a/.travis/pushdoc
+++ b/.travis/pushdoc
@@ -151,4 +151,12 @@ git add --all .
 # >/dev/null to avoid excessive noise on travis log
 git commit -m "Update to ${GIT_OWNER}/${GIT_REPO}@$hash" >/dev/null
 # -q and 2> is not to show the GIT_TOKEN on Travis log
-git push -q -f doc gh-pages 2> /dev/null 
+git push -q -f doc gh-pages 2> /dev/null || {
+  echo "++++ WARNING ++++"
+  echo "Pushing on repository https://${GIT_BOT}@github.com/$GIT_OWNER/doc-${BRANCH}.git failed"
+  echo "Please check if the repository exists"
+  if [[ "$branchtype" != unofficial ]] ; then
+     echo "This is an error on official, unsupported, and master branches"
+     exit 1
+  fi
+}
