added macsimple workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -147,3 +147,26 @@ jobs:
       run: |
         # these can fail for numerical reasons in Catalina with v2.4
         sudo port -N -d test plumed ${{ matrix.variant }} || true
+
+  macsimple:
+    runs-on: macos-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: Set paths
+      run: |
+        echo "$HOME/opt/bin" >> $GITHUB_PATH
+        echo "CPATH=$HOME/opt/include:$CPATH" >> $GITHUB_ENV
+        echo "INCLUDE=$HOME/opt/include:$INCLUDE" >> $GITHUB_ENV
+        echo "LIBRARY_PATH=$HOME/opt/lib:$LIBRARY_PATH" >> $GITHUB_ENV
+        echo "LD_LIBRARY_PATH=$HOME/opt/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
+    - name: Build PLUMED
+      run: |
+        brew update > /dev/null
+        ./configure --disable-dependency-tracking
+        make -j 4
+        make install prefix="$HOME/opt"
+    - name: Run tests
+      run: |
+         make --no-print-directory -C regtest
+         # these can fail for numerical reasons
+         make -C regtest checkfail || true
